### ISSUE TITLE
Test failure on i686

### ISSUE THREAD

**Issue by adigitoleo** [ivan-tkatchev/tab#8]
I get a test failure when building v9.2 on i686, with the traceback of:

```
Traceback (most recent call last):
  File "/builddir/tab-9.2/test/go.py", line 68, in <module>
    go(sort=("-s" in sys.argv), tests=sys.argv[1:])
  File "/builddir/tab-9.2/test/go.py", line 53, in go
    run(i, txt[1], txt[2], log, infile=txt[0].replace('\n',''), sort=sort)
  File "/builddir/tab-9.2/test/go.py", line 37, in run
    raise Exception("Test failed for: %s, '%s' -- output is '%s'" % (filename, arg, out))
Exception: Test failed for: uniques.test.in, 'z = { x=cut(@,"\t"), uint(x~0)/50 -> uniques.x~3, uniques_estimate.x~3 }, lines(sort.z, merge.first.second.z)' -- output is '38	221	330
39	589	834
40	528	783
608
'
```

Is 32-bit arch supported?

**Comment by ivan-tkatchev** [comment]
Yes, 32-bit architecture is supported. This is a test problem - uniques_estimate uses a hash under the hood that differs for 32 and 64 bit architectures.

I just pushed a test fix to master, please confirm that tests pass.

**Comment by adigitoleo** [comment]
Yes, it seems like that fixed it. Tests pass on the 32-bit runners now: https://github.com/void-linux/void-packages/actions/runs/8333452792/job/22804931888?pr=49358
